apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-data-generator
  namespace: ${namespace}
  labels:
    app: data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
      - name: generator
        image: amazon/aws-cli:latest
        command: ["/bin/bash"]
        args:
          - -c
          - |
            while true; do
              TIMESTAMP=$$(date +%s)
              USER_ID=$$(($${RANDOM} % 10000))
              AMOUNT=$$(($${RANDOM} % 10000))
              TRANSACTION='{"timestamp":'$$TIMESTAMP',"user_id":'$$USER_ID',"amount":'$$AMOUNT',"type":"trade"}'
              
              aws kinesis put-record \
                --stream-name ${trading_stream} \
                --partition-key $$USER_ID \
                --data "$$TRANSACTION" \
                --region ${aws_region}
              
              echo "Sent: $$TRANSACTION"
              sleep 1
            done
        env:
        - name: AWS_DEFAULT_REGION
          value: ${aws_region}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"