apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: fraud-detection
  namespace: ${namespace}
spec:
  image: public.ecr.aws/emr-on-eks/flink/flink:${flink_image_tag}
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "4"
    state.backend: rocksdb
    state.checkpoints.dir: s3://${bucket_name}/checkpoints/fraud-detection
    state.checkpoint-storage: filesystem
    execution.checkpointing.interval: 60s
    execution.checkpointing.mode: EXACTLY_ONCE
    restart-strategy: exponential-delay
    restart-strategy.exponential-delay.initial-backoff: 10s
    restart-strategy.exponential-delay.max-backoff: 2min
    restart-strategy.exponential-delay.backoff-multiplier: 2.0
    restart-strategy.exponential-delay.reset-backoff-threshold: 10min
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: s3://${bucket_name}/ha/fraud-detection
  serviceAccount: ${service_account}
  jobManager:
    resource:
      memory: 2048m
      cpu: 1
    replicas: 1
  taskManager:
    resource:
      memory: 4096m
      cpu: 2
    replicas: 3
  job:
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    parallelism: 6
    upgradeMode: stateless
    args:
      - "--input"
      - "kinesis"
      - "--aws.region"
      - "${aws_region}"
      - "--kinesis.stream.name"
      - "${trading_stream}"
      - "--output"
      - "s3://${bucket_name}/fraud-alerts/"
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: AWS_REGION
              value: ${aws_region}
            - name: ENABLE_NATIVE_S3_FILESYSTEM
              value: "true"
          volumeMounts:
            - name: flink-logs
              mountPath: /opt/flink/log
      volumes:
        - name: flink-logs
          emptyDir: {}