apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: risk-analytics
  namespace: ${namespace}
spec:
  image: public.ecr.aws/emr-on-eks/flink/flink:${flink_image_tag}
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    state.backend: rocksdb
    state.checkpoints.dir: s3://${bucket_name}/checkpoints/risk-analytics
    state.checkpoint-storage: filesystem
    execution.checkpointing.interval: 30s
    execution.checkpointing.mode: EXACTLY_ONCE
    restart-strategy: exponential-delay
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: s3://${bucket_name}/ha/risk-analytics
    metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prom.host: localhost
    metrics.reporter.prom.port: 9249
  serviceAccount: ${service_account}
  jobManager:
    resource:
      memory: 1536m
      cpu: 1
    replicas: 1
  taskManager:
    resource:
      memory: 2048m
      cpu: 1
    replicas: 2
  job:
    jarURI: local:///opt/flink/examples/streaming/WindowJoin.jar
    parallelism: 4
    upgradeMode: stateless
    args:
      - "--input"
      - "kinesis"
      - "--aws.region"
      - "${aws_region}"
      - "--kinesis.stream.name"
      - "${market_stream}"
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: AWS_REGION
              value: ${aws_region}
            - name: ENABLE_NATIVE_S3_FILESYSTEM
              value: "true"
          ports:
            - name: metrics
              containerPort: 9249
              protocol: TCP