# Vertical Pod Autoscaler CRDs and Components
# Note: This is a simplified version. For production use, install VPA using the official installation script
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: verticalpodautoscalers.autoscaling.k8s.io
spec:
  group: autoscaling.k8s.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              targetRef:
                type: object
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
              updatePolicy:
                type: object
                properties:
                  updateMode:
                    type: string
                    enum: ["Off", "Initial", "Recreate", "Auto"]
              resourcePolicy:
                type: object
                properties:
                  containerPolicies:
                    type: array
                    items:
                      type: object
                      properties:
                        containerName:
                          type: string
                        maxAllowed:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                        minAllowed:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
          status:
            type: object
            properties:
              recommendation:
                type: object
                properties:
                  containerRecommendations:
                    type: array
                    items:
                      type: object
                      properties:
                        containerName:
                          type: string
                        target:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                        uncappedTarget:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
  scope: Namespaced
  names:
    plural: verticalpodautoscalers
    singular: verticalpodautoscaler
    kind: VerticalPodAutoscaler
    shortNames:
    - vpa
---
# VPA configuration for CPU demo application
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cpu-demo-vpa
  namespace: demo-apps
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-demo
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: cpu-demo
      maxAllowed:
        cpu: 1
        memory: 1Gi
      minAllowed:
        cpu: 100m
        memory: 128Mi
---
# VPA configuration for memory demo application
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: memory-demo-vpa
  namespace: demo-apps
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: memory-demo
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: memory-demo
      maxAllowed:
        cpu: 500m
        memory: 2Gi
      minAllowed:
        cpu: 50m
        memory: 256Mi