# Infrastructure Manager Configuration for Secure AI Model Training Workflows
# This configuration deploys Dynamic Workload Scheduler and Confidential Computing
# infrastructure for secure AI model training with TEE protection
#
# Author: Infrastructure Generator v1.3
# Recipe: Secure AI Model Training Workflows with Dynamic Workload Scheduler and Confidential Computing
# Last Updated: 2025-07-12

# Infrastructure Manager uses Terraform configurations stored in Cloud Storage or Git
# This YAML file defines the deployment configuration for Infrastructure Manager

apiVersion: config.gcp.crossplane.io/v1beta1
kind: DeploymentManagerConfig
metadata:
  name: secure-ai-training-infrastructure
  annotations:
    config.kubernetes.io/local-config: "true"
    recipe.id: "f7a4e9c2"
    recipe.version: "1.0"
    generator.version: "1.3"
spec:
  # Project Configuration
  project: ${PROJECT_ID}
  
  # Deployment Metadata
  deployment:
    name: secure-ai-training-deployment
    description: "Secure AI model training infrastructure with Dynamic Workload Scheduler and Confidential Computing"
    labels:
      environment: production
      application: ai-training
      security-level: confidential
      cost-center: ml-engineering
      recipe-id: f7a4e9c2
    
  # Infrastructure Manager Configuration
  terraformConfig:
    # Terraform configuration source (Cloud Storage bucket)
    source:
      # Note: This would typically reference a Cloud Storage bucket or Git repository
      # containing the Terraform configuration files
      storageSource:
        bucket: ${PROJECT_ID}-terraform-configs
        object: secure-ai-training/main.tf
        generation: 1
    
    # Terraform Variables
    inputValues:
      # Project and Location Configuration
      project_id:
        inputValue: ${PROJECT_ID}
      region:
        inputValue: us-central1
      zone:
        inputValue: us-central1-a
      
      # Resource Naming Configuration
      deployment_name:
        inputValue: secure-ai-training
      random_suffix:
        inputValue: ${RANDOM_SUFFIX}
      
      # Cloud KMS Configuration
      kms_keyring_name:
        inputValue: ai-training-keyring-${RANDOM_SUFFIX}
      kms_key_name:
        inputValue: training-data-key
      kms_rotation_period:
        inputValue: 2592000s  # 30 days
      
      # Cloud Storage Configuration
      training_data_bucket:
        inputValue: secure-training-data-${RANDOM_SUFFIX}
      storage_class:
        inputValue: STANDARD
      versioning_enabled:
        inputValue: true
      
      # Service Account Configuration
      service_account_name:
        inputValue: ai-training-sa
      service_account_display_name:
        inputValue: "AI Training Confidential Computing Service Account"
      
      # Confidential Computing Configuration
      confidential_vm_name:
        inputValue: confidential-training-vm
      machine_type:
        inputValue: a2-highgpu-1g
      accelerator_type:
        inputValue: nvidia-tesla-a100
      accelerator_count:
        inputValue: 1
      boot_disk_size:
        inputValue: 100
      boot_disk_type:
        inputValue: pd-ssd
      
      # Dynamic Workload Scheduler Configuration
      reservation_name:
        inputValue: secure-ai-training-reservation
      vm_count:
        inputValue: 1
      reservation_affinity:
        inputValue: specific
      
      # Instance Template Configuration
      instance_template_name:
        inputValue: confidential-training-template
      image_family:
        inputValue: deep-learning-vm
      image_project:
        inputValue: ml-images
      
      # Vertex AI Configuration
      vertex_job_display_name:
        inputValue: "Secure AI Training Job"
      vertex_container_image:
        inputValue: gcr.io/deeplearning-platform-release/pytorch-gpu.1-13
      
      # Security Configuration
      enable_confidential_compute:
        inputValue: true
      confidential_compute_type:
        inputValue: SEV
      enable_oslogin:
        inputValue: true
      
      # Monitoring Configuration
      enable_monitoring:
        inputValue: true
      enable_audit_logging:
        inputValue: true
      monitoring_policy_name:
        inputValue: confidential-training-security-policy
      
      # Network Configuration
      network_tags:
        inputValue: ["confidential-training", "secure-ai", "high-security"]
      
      # Cost Optimization Configuration
      storage_lifecycle_enabled:
        inputValue: true
      nearline_age_days:
        inputValue: 30
      coldline_age_days:
        inputValue: 90
      
      # Compliance Configuration
      enable_binary_authorization:
        inputValue: true
      enable_vulnerability_scanning:
        inputValue: true
      attestation_required:
        inputValue: true

  # Terraform Resources Configuration
  resources:
    # Cloud KMS Resources
    - name: kms-keyring
      type: google_kms_key_ring
      properties:
        name: ${kms_keyring_name}
        location: ${region}
        project: ${project_id}
    
    - name: kms-crypto-key
      type: google_kms_crypto_key
      properties:
        name: ${kms_key_name}
        key_ring: ${kms-keyring.id}
        rotation_period: ${kms_rotation_period}
        purpose: ENCRYPT_DECRYPT
        version_template:
          algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
          protection_level: SOFTWARE
    
    # IAM Service Account Resources
    - name: training-service-account
      type: google_service_account
      properties:
        account_id: ${service_account_name}
        display_name: ${service_account_display_name}
        description: "Service account for secure AI training in confidential computing environment"
        project: ${project_id}
    
    # Service Account IAM Bindings
    - name: sa-aiplatform-user-binding
      type: google_project_iam_member
      properties:
        project: ${project_id}
        role: roles/aiplatform.user
        member: serviceAccount:${training-service-account.email}
    
    - name: sa-storage-admin-binding
      type: google_project_iam_member
      properties:
        project: ${project_id}
        role: roles/storage.objectAdmin
        member: serviceAccount:${training-service-account.email}
    
    - name: sa-kms-encrypter-binding
      type: google_project_iam_member
      properties:
        project: ${project_id}
        role: roles/cloudkms.cryptoKeyEncrypterDecrypter
        member: serviceAccount:${training-service-account.email}
    
    - name: sa-confidential-compute-binding
      type: google_project_iam_member
      properties:
        project: ${project_id}
        role: roles/confidentialcomputing.workloadUser
        member: serviceAccount:${training-service-account.email}
    
    # Cloud Storage Resources
    - name: training-data-bucket
      type: google_storage_bucket
      properties:
        name: ${training_data_bucket}
        location: ${region}
        project: ${project_id}
        storage_class: ${storage_class}
        versioning:
          enabled: ${versioning_enabled}
        encryption:
          default_kms_key_name: ${kms-crypto-key.id}
        lifecycle_rule:
          - condition:
              age: ${nearline_age_days}
            action:
              type: SetStorageClass
              storage_class: NEARLINE
          - condition:
              age: ${coldline_age_days}
            action:
              type: SetStorageClass
              storage_class: COLDLINE
        uniform_bucket_level_access: true
        public_access_prevention: enforced
    
    # Compute Engine Resources - Dynamic Workload Scheduler
    - name: gpu-reservation
      type: google_compute_reservation
      properties:
        name: ${reservation_name}
        zone: ${zone}
        project: ${project_id}
        specific_reservation:
          count: ${vm_count}
          instance_properties:
            machine_type: ${machine_type}
            guest_accelerators:
              - accelerator_type: ${accelerator_type}
                accelerator_count: ${accelerator_count}
        specific_reservation_required: true
    
    # Instance Template for Confidential Computing
    - name: confidential-instance-template
      type: google_compute_instance_template
      properties:
        name: ${instance_template_name}
        project: ${project_id}
        description: "Instance template for confidential AI training workloads"
        machine_type: ${machine_type}
        
        # Confidential Computing Configuration
        confidential_instance_config:
          enable_confidential_compute: ${enable_confidential_compute}
          confidential_instance_type: ${confidential_compute_type}
        
        # GPU Acceleration
        guest_accelerator:
          - type: ${accelerator_type}
            count: ${accelerator_count}
        
        # Boot Disk Configuration
        disk:
          - source_image: projects/${image_project}/global/images/family/${image_family}
            auto_delete: true
            boot: true
            disk_size_gb: ${boot_disk_size}
            disk_type: ${boot_disk_type}
            disk_encryption_key:
              kms_key_self_link: ${kms-crypto-key.id}
        
        # Network Configuration
        network_interface:
          - network: default
            access_config:
              - network_tier: PREMIUM
        
        # Service Account Configuration
        service_account:
          - email: ${training-service-account.email}
            scopes: 
              - https://www.googleapis.com/auth/cloud-platform
        
        # Security and Metadata
        metadata:
          enable-oslogin: ${enable_oslogin}
          google-logging-enabled: true
          google-monitoring-enabled: true
          startup-script: |
            #!/bin/bash
            # Configure confidential computing environment
            echo "Initializing secure AI training environment..."
            
            # Install required packages for ML workloads
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install --upgrade google-cloud-storage google-cloud-aiplatform
            
            # Configure GPU drivers if needed
            sudo nvidia-smi -pm 1
            
            echo "Confidential training environment ready"
        
        tags: ${network_tags}
        
        # Reservation Configuration
        reservation_affinity:
          type: SPECIFIC_RESERVATION
          specific_reservation:
            key: compute.googleapis.com/reservation-name
            values: [${gpu-reservation.name}]
    
    # Confidential Computing VM Instance
    - name: confidential-training-vm
      type: google_compute_instance
      properties:
        name: ${confidential_vm_name}
        zone: ${zone}
        project: ${project_id}
        
        # Use the confidential instance template
        machine_type: ${machine_type}
        
        # Confidential Computing Configuration
        confidential_instance_config:
          enable_confidential_compute: ${enable_confidential_compute}
          confidential_instance_type: ${confidential_compute_type}
        
        # GPU Configuration
        guest_accelerator:
          - type: ${accelerator_type}
            count: ${accelerator_count}
        
        # Boot Disk
        boot_disk:
          initialize_params:
            image: projects/${image_project}/global/images/family/${image_family}
            size: ${boot_disk_size}
            type: ${boot_disk_type}
          kms_key_self_link: ${kms-crypto-key.id}
        
        # Network Configuration
        network_interface:
          - network: default
            access_config:
              - network_tier: PREMIUM
        
        # Service Account
        service_account:
          - email: ${training-service-account.email}
            scopes:
              - https://www.googleapis.com/auth/cloud-platform
        
        # Metadata and Security
        metadata:
          enable-oslogin: ${enable_oslogin}
          google-logging-enabled: true
          google-monitoring-enabled: true
        
        tags: ${network_tags}
        
        # Scheduling for reservation
        scheduling:
          on_host_maintenance: TERMINATE
          automatic_restart: true
          preemptible: false
        
        # Reservation Affinity
        reservation_affinity:
          type: SPECIFIC_RESERVATION
          specific_reservation:
            key: compute.googleapis.com/reservation-name
            values: [${gpu-reservation.name}]
        
        # Labels for resource management
        labels:
          environment: production
          workload-type: confidential-ai
          security-level: high
          cost-center: ml-engineering
    
    # Cloud Monitoring Resources
    - name: confidential-training-monitoring-policy
      type: google_monitoring_alert_policy
      properties:
        display_name: ${monitoring_policy_name}
        project: ${project_id}
        documentation:
          content: "Alert policy for monitoring confidential AI training security events"
        conditions:
          - display_name: "TEE Attestation Failure"
            condition_threshold:
              filter: 'resource.type="gce_instance" AND metric.type="compute.googleapis.com/instance/confidential_compute/attestation_failure"'
              comparison: COMPARISON_GREATER_THAN
              threshold_value: 0
              duration: 60s
        alert_strategy:
          auto_close: 86400s
        enabled: ${enable_monitoring}
    
    # Cloud Logging Resources for Audit Trail
    - name: confidential-training-log-sink
      type: google_logging_project_sink
      properties:
        name: confidential-training-audit
        project: ${project_id}
        destination: storage.googleapis.com/${training-data-bucket}/audit-logs
        filter: 'protoPayload.serviceName=("compute.googleapis.com" OR "confidentialcomputing.googleapis.com") AND resource.labels.instance_name="${confidential_vm_name}"'
        unique_writer_identity: true

  # Output Configuration
  outputs:
    # Project Information
    project_id:
      description: "Google Cloud Project ID"
      value: ${project_id}
    
    region:
      description: "Deployment region"
      value: ${region}
    
    zone:
      description: "Deployment zone"
      value: ${zone}
    
    # KMS Information
    kms_keyring_id:
      description: "Cloud KMS KeyRing ID"
      value: ${kms-keyring.id}
    
    kms_key_id:
      description: "Cloud KMS Crypto Key ID"
      value: ${kms-crypto-key.id}
    
    # Storage Information
    training_bucket_name:
      description: "Training data bucket name"
      value: ${training-data-bucket.name}
    
    training_bucket_url:
      description: "Training data bucket URL"
      value: ${training-data-bucket.url}
    
    # Service Account Information
    service_account_email:
      description: "Service account email for AI training"
      value: ${training-service-account.email}
    
    service_account_id:
      description: "Service account unique ID"
      value: ${training-service-account.unique_id}
    
    # Compute Resources Information
    reservation_id:
      description: "GPU reservation ID"
      value: ${gpu-reservation.id}
    
    instance_template_id:
      description: "Confidential instance template ID"
      value: ${confidential-instance-template.id}
    
    confidential_vm_name:
      description: "Confidential VM instance name"
      value: ${confidential-training-vm.name}
    
    confidential_vm_internal_ip:
      description: "Confidential VM internal IP address"
      value: ${confidential-training-vm.network_interface.0.network_ip}
    
    confidential_vm_external_ip:
      description: "Confidential VM external IP address"
      value: ${confidential-training-vm.network_interface.0.access_config.0.nat_ip}
    
    # Security Information
    attestation_enabled:
      description: "Confidential computing attestation status"
      value: ${enable_confidential_compute}
    
    kms_encryption_enabled:
      description: "KMS encryption status"
      value: true
    
    # Monitoring Information
    monitoring_policy_id:
      description: "Cloud Monitoring alert policy ID"
      value: ${confidential-training-monitoring-policy.id}
    
    log_sink_id:
      description: "Cloud Logging sink ID for audit trail"
      value: ${confidential-training-log-sink.id}
    
    # Cost Optimization Information
    reservation_commitment:
      description: "GPU reservation commitment details"
      value: "1x ${machine_type} with ${accelerator_count}x ${accelerator_type}"
    
    estimated_hourly_cost:
      description: "Estimated hourly cost for compute resources (USD)"
      value: "~$3.50-5.00 per hour for A100 GPU + confidential computing"

# Deployment Instructions
# 
# To deploy this infrastructure using Infrastructure Manager:
#
# 1. Upload the Terraform configuration to Cloud Storage:
#    gsutil cp -r terraform-configs/ gs://${PROJECT_ID}-terraform-configs/secure-ai-training/
#
# 2. Create the Infrastructure Manager deployment:
#    gcloud infra-manager deployments create secure-ai-training-deployment \
#        --location=${REGION} \
#        --service-account=${SERVICE_ACCOUNT_EMAIL} \
#        --terraform-config=secure-ai-training/main.tf \
#        --input-values=project_id=${PROJECT_ID},region=${REGION}
#
# 3. Monitor deployment progress:
#    gcloud infra-manager deployments describe secure-ai-training-deployment \
#        --location=${REGION}
#
# 4. To update the deployment:
#    gcloud infra-manager revisions create \
#        --deployment=secure-ai-training-deployment \
#        --location=${REGION}
#
# 5. To delete the deployment:
#    gcloud infra-manager deployments delete secure-ai-training-deployment \
#        --location=${REGION}

# Security Considerations:
# - All data is encrypted at rest using Cloud KMS customer-managed keys
# - Confidential Computing provides runtime encryption and isolation
# - Service accounts follow principle of least privilege
# - Network access is restricted through security groups and firewall rules
# - Audit logging captures all administrative and data access events
# - Binary Authorization ensures only trusted container images are deployed
# - Attestation services provide cryptographic proof of TEE integrity

# Cost Optimization Features:
# - Dynamic Workload Scheduler reservation reduces GPU costs by up to 70%
# - Storage lifecycle policies automatically tier data to reduce costs
# - Preemptible instances can be used for non-critical training workloads
# - Monitoring alerts help prevent cost overruns
# - Resource labels enable detailed cost allocation and chargeback

# Compliance and Governance:
# - Comprehensive audit logging for SOX, HIPAA, and other compliance frameworks
# - Attestation services provide evidence for security audits
# - Resource tagging enables governance and cost allocation
# - IAM policies ensure appropriate access controls
# - Data residency controls ensure data remains in specified regions