# Google Cloud Infrastructure Manager Configuration
# Healthcare Data Processing with Cloud Batch and Vertex AI Agents
# 
# This configuration deploys a complete healthcare data processing pipeline
# that combines Cloud Batch for scalable compute orchestration with Vertex AI
# Agent Builder for intelligent medical record analysis, ensuring HIPAA compliance
# and FHIR-standard data handling throughout the workflow.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: healthcare-data-processing-batch-vertex-ai
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Healthcare Data Processing with Cloud Batch and Vertex AI Agents
    source:
      repo: https://github.com/GoogleCloudPlatform/healthcare-ai-recipes
      sourceType: git
    version: 1.0.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.5"
    description:
      tagline: Scalable healthcare data processing with AI-powered analysis and HIPAA compliance
      detailed: |
        This blueprint deploys an intelligent healthcare data processing pipeline that combines:
        - Cloud Batch for auto-scaling compute orchestration
        - Vertex AI Agent Builder for medical record analysis
        - Cloud Healthcare API for FHIR-compliant data storage
        - Cloud Storage for secure data ingestion
        - Cloud Functions for event-driven processing
        - Comprehensive monitoring and compliance tracking

---
# Project Configuration
# Defines the GCP project and required APIs for healthcare data processing
imports:
- path: modules/project-services.yaml
- path: modules/healthcare-storage.yaml
- path: modules/healthcare-api.yaml
- path: modules/vertex-ai-agent.yaml
- path: modules/batch-processing.yaml
- path: modules/cloud-functions.yaml
- path: modules/monitoring-compliance.yaml

resources:
# Enable Required APIs
# Healthcare API, Batch, Vertex AI, Storage, Functions, Logging, Monitoring
- name: project-services
  type: modules/project-services.yaml
  properties:
    project_id: $(ref.project.projectId)
    services:
      - healthcare.googleapis.com
      - batch.googleapis.com
      - aiplatform.googleapis.com
      - storage.googleapis.com
      - cloudfunctions.googleapis.com
      - logging.googleapis.com
      - monitoring.googleapis.com
      - pubsub.googleapis.com
      - secretmanager.googleapis.com
      - audit.googleapis.com

# Healthcare Data Storage
# HIPAA-compliant Cloud Storage bucket with versioning and audit logging
- name: healthcare-storage
  type: modules/healthcare-storage.yaml
  properties:
    project_id: $(ref.project.projectId)
    region: us-central1
    bucket_name: healthcare-data-$(ref.random-suffix.hex)
    storage_class: STANDARD
    versioning_enabled: true
    uniform_bucket_level_access: true
    public_access_prevention: enforced
    lifecycle_rules:
      - action:
          type: Delete
        condition:
          age: 2555  # 7 years retention for healthcare data
          with_state: ARCHIVED
      - action:
          type: SetStorageClass
          storage_class: COLDLINE
        condition:
          age: 90  # Move to coldline after 90 days
    audit_logging:
      log_bucket: $(ref.audit-log-bucket.name)
      retention_days: 2555  # 7 years for HIPAA compliance

# Cloud Healthcare API Setup
# FHIR-compliant dataset and store for structured medical data
- name: healthcare-api
  type: modules/healthcare-api.yaml
  properties:
    project_id: $(ref.project.projectId)
    region: us-central1
    dataset_id: healthcare-dataset-$(ref.random-suffix.hex)
    fhir_store_id: patient-records-$(ref.random-suffix.hex)
    fhir_version: R4
    enable_update_create: true
    notification_config:
      pubsub_topic: $(ref.healthcare-notifications.name)
    labels:
      purpose: healthcare-ai-processing
      environment: production
      compliance: hipaa

# Vertex AI Agent Configuration
# Healthcare-specialized AI agent for medical record analysis
- name: vertex-ai-agent
  type: modules/vertex-ai-agent.yaml
  properties:
    project_id: $(ref.project.projectId)
    region: us-central1
    agent_name: healthcare-records-analyzer
    display_name: Healthcare Records Analyzer
    description: AI agent for intelligent healthcare data processing and compliance monitoring
    service_account: $(ref.healthcare-ai-service-account.email)
    tools:
      - name: healthcare_nlp_tool
        description: Healthcare Natural Language Processing for clinical text analysis
      - name: compliance_checker_tool
        description: HIPAA compliance validation and PHI detection
      - name: clinical_insights_extractor
        description: Extract structured clinical insights from medical records
      - name: fhir_converter_tool
        description: Convert processed data to FHIR-compliant format
    instructions: |
      You are a healthcare AI agent specialized in medical record analysis.
      Your primary responsibilities include:
      1. Processing medical documents while maintaining strict HIPAA compliance
      2. Extracting clinical insights and structured data from unstructured medical text
      3. Identifying critical findings that require immediate attention
      4. Converting processed data to FHIR-compliant format
      5. Ensuring data accuracy and clinical relevance
      6. Monitoring for potential compliance violations or PHI exposure
      
      Always prioritize patient privacy, data security, and regulatory compliance.
      Flag any suspicious or non-compliant data for manual review.
    model_config:
      model_name: gemini-1.5-pro
      temperature: 0.1  # Low temperature for consistent medical analysis
      max_output_tokens: 4096

# Cloud Batch Job Template
# Scalable compute orchestration for healthcare data processing
- name: batch-processing
  type: modules/batch-processing.yaml
  properties:
    project_id: $(ref.project.projectId)
    region: us-central1
    job_template_name: healthcare-processing-template
    service_account: $(ref.batch-service-account.email)
    machine_type: e2-standard-4
    cpu_milli: 4000
    memory_mib: 8192
    max_retry_count: 3
    max_run_duration: 3600s
    task_count: 1
    parallelism: 1
    boot_disk:
      size_gb: 50
      type: pd-standard
    container_image: gcr.io/$(ref.project.projectId)/healthcare-processor:latest
    environment_variables:
      PROJECT_ID: $(ref.project.projectId)
      REGION: us-central1
      BUCKET_NAME: $(ref.healthcare-storage.bucket_name)
      FHIR_STORE_ID: $(ref.healthcare-api.fhir_store_id)
      DATASET_ID: $(ref.healthcare-api.dataset_id)
      VERTEX_AI_LOCATION: us-central1
    network:
      network: $(ref.vpc-network.selfLink)
      subnetwork: $(ref.private-subnet.selfLink)
    labels:
      purpose: healthcare-processing
      compliance: hipaa
      environment: production

# Cloud Functions for Event-Driven Processing
# Serverless compute for automated job triggering and workflow orchestration
- name: cloud-functions
  type: modules/cloud-functions.yaml
  properties:
    project_id: $(ref.project.projectId)
    region: us-central1
    functions:
      - name: healthcare-processor-trigger
        description: Trigger healthcare data processing when files are uploaded
        runtime: python311
        memory_mb: 512
        timeout: 540s
        entry_point: trigger_healthcare_processing
        service_account: $(ref.function-service-account.email)
        environment_variables:
          PROJECT_ID: $(ref.project.projectId)
          REGION: us-central1
          BUCKET_NAME: $(ref.healthcare-storage.bucket_name)
          BATCH_JOB_TEMPLATE: $(ref.batch-processing.job_template_name)
        event_trigger:
          event_type: google.storage.object.finalize
          resource: $(ref.healthcare-storage.bucket_name)
          retry_policy: RETRY_POLICY_RETRY
        source_code_bucket: $(ref.function-source-bucket.name)
        labels:
          purpose: healthcare-automation
          compliance: hipaa

      - name: compliance-monitor
        description: Monitor healthcare processing for compliance violations
        runtime: python311
        memory_mb: 256
        timeout: 300s
        entry_point: monitor_compliance
        service_account: $(ref.function-service-account.email)
        environment_variables:
          PROJECT_ID: $(ref.project.projectId)
          ALERT_TOPIC: $(ref.compliance-alerts.name)
        event_trigger:
          event_type: google.pubsub.topic.publish
          resource: $(ref.healthcare-notifications.name)
        source_code_bucket: $(ref.function-source-bucket.name)

# Monitoring and Compliance Tracking
# Comprehensive observability and audit trail for healthcare data processing
- name: monitoring-compliance
  type: modules/monitoring-compliance.yaml
  properties:
    project_id: $(ref.project.projectId)
    notification_channels:
      - display_name: Healthcare Operations Team
        type: email
        labels:
          email_address: healthcare-ops@company.com
    dashboards:
      - name: healthcare-processing-dashboard
        display_name: Healthcare Data Processing Dashboard
        tiles:
          - title: Batch Job Success Rate
            type: scorecard
            filter: resource.type="batch_job"
            aggregation: success_rate
          - title: Processing Latency
            type: xy_chart
            filter: resource.type="cloud_function"
            metric: execution_time
          - title: Compliance Violations
            type: scorecard
            filter: severity="ERROR" AND resource.type="healthcare_dataset"
            aggregation: count
          - title: Data Volume Processed
            type: xy_chart
            filter: resource.type="gcs_bucket"
            metric: object_count
    alert_policies:
      - display_name: HIPAA Compliance Violation Alert
        conditions:
          - display_name: Compliance Violation Detected
            filter: resource.type="healthcare_dataset" AND severity="ERROR"
            comparison: COMPARISON_GREATER_THAN
            threshold_value: 0
            duration: 60s
        notification_channels: $(ref.email-notification-channel.name)
        alert_strategy:
          auto_close: 1800s
      - display_name: Batch Job Failure Alert
        conditions:
          - display_name: Multiple Job Failures
            filter: resource.type="batch_job" AND status="FAILED"
            comparison: COMPARISON_GREATER_THAN
            threshold_value: 2
            duration: 300s
        notification_channels: $(ref.email-notification-channel.name)
      - display_name: High Processing Latency Alert
        conditions:
          - display_name: Processing Time Exceeded
            filter: resource.type="cloud_function" AND function_name="healthcare-processor-trigger"
            comparison: COMPARISON_GREATER_THAN
            threshold_value: 300
            duration: 180s
        notification_channels: $(ref.email-notification-channel.name)

# Service Accounts and IAM
# Least-privilege access control for healthcare data processing components
- name: healthcare-ai-service-account
  type: gcp-types/iam-v1:serviceAccount
  properties:
    accountId: healthcare-ai-agent
    displayName: Healthcare AI Analysis Agent
    description: Service account for AI-powered healthcare data analysis
    project: $(ref.project.projectId)

- name: batch-service-account
  type: gcp-types/iam-v1:serviceAccount
  properties:
    accountId: healthcare-batch-processor
    displayName: Healthcare Batch Processing Service
    description: Service account for Cloud Batch healthcare processing jobs
    project: $(ref.project.projectId)

- name: function-service-account
  type: gcp-types/iam-v1:serviceAccount
  properties:
    accountId: healthcare-function-runner
    displayName: Healthcare Cloud Functions Runner
    description: Service account for healthcare processing Cloud Functions
    project: $(ref.project.projectId)

# IAM Bindings for Healthcare Data Access
- name: healthcare-ai-iam-bindings
  type: gcp-types/cloudresourcemanager-v1:virtual.projects.iamMemberBinding
  properties:
    resource: $(ref.project.projectId)
    role: roles/aiplatform.user
    member: serviceAccount:$(ref.healthcare-ai-service-account.email)

- name: healthcare-fhir-iam-bindings
  type: gcp-types/cloudresourcemanager-v1:virtual.projects.iamMemberBinding
  properties:
    resource: $(ref.project.projectId)
    role: roles/healthcare.fhirResourceEditor
    member: serviceAccount:$(ref.healthcare-ai-service-account.email)

- name: batch-storage-iam-bindings
  type: gcp-types/cloudresourcemanager-v1:virtual.projects.iamMemberBinding
  properties:
    resource: $(ref.project.projectId)
    role: roles/storage.objectViewer
    member: serviceAccount:$(ref.batch-service-account.email)

- name: function-batch-iam-bindings
  type: gcp-types/cloudresourcemanager-v1:virtual.projects.iamMemberBinding
  properties:
    resource: $(ref.project.projectId)
    role: roles/batch.jobsEditor
    member: serviceAccount:$(ref.function-service-account.email)

# Networking Configuration
# Secure VPC setup for healthcare data processing workloads
- name: vpc-network
  type: gcp-types/compute-v1:network
  properties:
    name: healthcare-processing-vpc
    description: VPC network for healthcare data processing workloads
    autoCreateSubnetworks: false
    project: $(ref.project.projectId)

- name: private-subnet
  type: gcp-types/compute-v1:subnetwork
  properties:
    name: healthcare-private-subnet
    description: Private subnet for healthcare processing resources
    network: $(ref.vpc-network.selfLink)
    ipCidrRange: 10.0.1.0/24
    region: us-central1
    project: $(ref.project.projectId)
    privateIpGoogleAccess: true
    logConfig:
      enable: true
      aggregationInterval: INTERVAL_10_MIN
      flowSampling: 0.5

# Cloud NAT for Outbound Internet Access
- name: nat-router
  type: gcp-types/compute-v1:router
  properties:
    name: healthcare-nat-router
    description: NAT router for healthcare processing subnet
    network: $(ref.vpc-network.selfLink)
    region: us-central1
    project: $(ref.project.projectId)

- name: nat-gateway
  type: gcp-types/compute-v1:routerNat
  properties:
    name: healthcare-nat-gateway
    router: $(ref.nat-router.name)
    region: us-central1
    project: $(ref.project.projectId)
    natIpAllocateOption: AUTO_ONLY
    sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
    logConfig:
      enable: true
      filter: ERRORS_ONLY

# Firewall Rules for Secure Access
- name: healthcare-firewall-rules
  type: gcp-types/compute-v1:firewall
  properties:
    name: allow-healthcare-internal
    description: Allow internal communication within healthcare VPC
    network: $(ref.vpc-network.selfLink)
    project: $(ref.project.projectId)
    sourceRanges:
      - 10.0.1.0/24
    allowed:
      - IPProtocol: tcp
        ports:
          - "80"
          - "443"
          - "8080"
    direction: INGRESS
    priority: 1000

# Pub/Sub Topics for Event-Driven Architecture
- name: healthcare-notifications
  type: gcp-types/pubsub-v1:topic
  properties:
    name: healthcare-processing-notifications
    project: $(ref.project.projectId)
    labels:
      purpose: healthcare-notifications
      compliance: hipaa

- name: compliance-alerts
  type: gcp-types/pubsub-v1:topic
  properties:
    name: compliance-violation-alerts
    project: $(ref.project.projectId)
    labels:
      purpose: compliance-alerts
      compliance: hipaa

# Audit Logging Bucket
- name: audit-log-bucket
  type: gcp-types/storage-v1:bucket
  properties:
    name: healthcare-audit-logs-$(ref.random-suffix.hex)
    project: $(ref.project.projectId)
    location: us-central1
    storageClass: STANDARD
    versioning:
      enabled: true
    lifecycle:
      rule:
        - action:
            type: Delete
          condition:
            age: 2555  # 7 years retention
    uniformBucketLevelAccess:
      enabled: true
    publicAccessPrevention: enforced
    labels:
      purpose: audit-logging
      compliance: hipaa

# Function Source Code Bucket
- name: function-source-bucket
  type: gcp-types/storage-v1:bucket
  properties:
    name: healthcare-function-source-$(ref.random-suffix.hex)
    project: $(ref.project.projectId)
    location: us-central1
    storageClass: STANDARD
    uniformBucketLevelAccess:
      enabled: true
    labels:
      purpose: function-source
      compliance: hipaa

# Random Suffix Generator for Unique Resource Names
- name: random-suffix
  type: gcp-types/random-v1:id
  properties:
    byte_length: 4

# Secret Manager for Sensitive Configuration
- name: healthcare-secrets
  type: gcp-types/secretmanager-v1:secret
  properties:
    secretId: healthcare-api-keys
    project: $(ref.project.projectId)
    replication:
      automatic: {}
    labels:
      purpose: healthcare-configuration
      compliance: hipaa

# Outputs
outputs:
- name: project_id
  value: $(ref.project.projectId)
  description: The GCP project ID where resources are deployed

- name: healthcare_bucket_name
  value: $(ref.healthcare-storage.bucket_name)
  description: Name of the Cloud Storage bucket for healthcare data

- name: healthcare_dataset_id
  value: $(ref.healthcare-api.dataset_id)
  description: ID of the Cloud Healthcare API dataset

- name: fhir_store_id
  value: $(ref.healthcare-api.fhir_store_id)
  description: ID of the FHIR store for patient records

- name: vertex_ai_agent_name
  value: $(ref.vertex-ai-agent.agent_name)
  description: Name of the Vertex AI agent for healthcare analysis

- name: batch_job_template
  value: $(ref.batch-processing.job_template_name)
  description: Name of the Cloud Batch job template

- name: processing_function_name
  value: $(ref.cloud-functions.functions[0].name)
  description: Name of the Cloud Function for processing triggers

- name: monitoring_dashboard_url
  value: https://console.cloud.google.com/monitoring/dashboards/custom/$(ref.monitoring-compliance.dashboards[0].name)?project=$(ref.project.projectId)
  description: URL to the healthcare processing monitoring dashboard

- name: vpc_network_name
  value: $(ref.vpc-network.name)
  description: Name of the VPC network for healthcare processing

- name: healthcare_ai_service_account
  value: $(ref.healthcare-ai-service-account.email)
  description: Email of the service account for healthcare AI operations

# Metadata for Infrastructure Manager
metadata:
  name: healthcare-data-processing-infrastructure
  annotations:
    deployment.cloud.google.com/name: healthcare-ai-processing
    deployment.cloud.google.com/environment: production
  labels:
    purpose: healthcare-ai-processing
    compliance: hipaa
    environment: production
    version: "1.0"